config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  get '/dashboard', to: 'events#index'
  resources :events
  resources :categories, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  color      :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_categories_on_user_id  (user_id)
#

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event

  scope :sort_by_date, -> { order(created_at: :desc )}
end

# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  comment    :text
#  event_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_comments_on_event_id  (event_id)
#

app/models/event.rb
class Event < ApplicationRecord
  has_attached_file :event_file

  belongs_to :user
  belongs_to :category, optional: true

  has_many :comments, inverse_of: :event, dependent: :destroy
  accepts_nested_attributes_for :comments, allow_destroy: true, reject_if: :all_blank

  has_many :tasks, inverse_of: :event, dependent: :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: :all_blank

  scope :active, -> { where(active: true) }

  validates :title, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates_attachment :event_file, content_type: { content_type: [
    "application/pdf",
    "application/doc",
    "application/docx",
    "image/jpeg",
    "image/jpg",
    "image/gif",
    "image/png"
  ] }

end

# == Schema Information
#
# Table name: events
#
#  id                      :integer          not null, primary key
#  title                   :string
#  description             :text
#  start_time              :datetime
#  end_time                :datetime
#  active                  :boolean          default(TRUE)
#  private                 :boolean          default(TRUE)
#  user_id                 :integer
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  event_file_file_name    :string
#  event_file_content_type :string
#  event_file_file_size    :integer
#  event_file_updated_at   :datetime
#  category_id             :integer
#  active_date             :date
#
# Indexes
#
#  index_events_on_category_id  (category_id)
#  index_events_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#

app/models/task.rb
class Task < ApplicationRecord
  enum priority: [:low, :medium, :high]

  belongs_to :event

  scope :sort_by_priority, -> { order(priority: :desc )}
end

# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  description :text
#  priority    :integer          default("low")
#  event_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_tasks_on_event_id  (event_id)
#

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy
  has_many :categories, dependent: :destroy
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  first_name             :string
#  last_name              :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:edit, :update]

  def new
    @category = current_user.categories.new
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      redirect_to dashboard_path
      flash[:notice] = "Category was created successfully."
    else
      flash.now[:error] = "Couldn't create category."
      render :new
    end
  end

  def edit
    @category
  end

  def update
    if @category.update(category_params)
      redirect_to dashboard_path
      flash[:notice] = "Category was updated successfully."
    else
      flash.now[:error] = "Couldn't update category."
      render :edit
    end
  end

  private

  def set_category
    @category = current_user.categories.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:id, :name, :color)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :activate_events, only: [:index]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def show
    @event
    @tasks = @event.tasks.sort_by_priority
    @comments = @event.comments.sort_by_date
  end

  def index
    @user = current_user
    @categories = current_user.categories
    @events = current_user.events.active
  end

  def new
    @event = current_user.events.new
  end

  def create
    @event = current_user.events.new(event_params)
    if @event.save
      redirect_to dashboard_path
      flash[:notice] = "Event was created successfully."
    else
      flash.now[:error] = "Couldn't create event."
      render :new
    end
  end

  def edit
    @event
  end

  def update
    if @event.update(event_params)
      redirect_to dashboard_path
      flash[:notice] = "Event was updated successfully."
    else
      flash.now[:error] = "Couldn't update event."
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to dashboard_path
    flash[:notice] = "Event was successfully destroyed."
  end

  private

  # my assumption around dates "turning on" was that they would become visible on a selected date.
  def activate_events
    current_user.events.where(active: false).where("active_date <= ?", Date.today ).update_all(active: true)
  end

  def set_event
    @event = current_user.events.find(params[:id])
  end

  def event_params
    params.require(:event).permit(
      :id,
      :title,
      :description,
      :start_time,
      :end_time,
      :event_file,
      :active,
      :active_date,
      :private,
      :category_id,
      comments_attributes: [:id, :comment, :_destroy],
      tasks_attributes: [:id, :description, :priority, :_destroy]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to dashboard_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/event_helper.rb
module EventHelper
  def listing_color(event)
    if event.category
      "#{event.category.color}"
    else
      "black"
    end
  end
end

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
  <%= f.error_notification message: t(:'simple_form.error_notification.default_message', model: "Category") %>

  <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>

  <div class="form-group row">
    <%= f.input :name, wrapper_html: { class: "col-8" }%>
    <%= f.input :color, as: :minicolors, wrapper_html: { class: "col-4" }, input_html: { class: "form-control", data: {
        minicolors: { theme: :bootstrap, position: :right }}} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, { class: "btn btn-info" } %>
    <%= link_to "Cancel", dashboard_path, { class: "btn btn-secondary" } %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="card">
  <h4 class="card-header"><%= "Edit #{@category.name}" %></h4>
  <div class="card-body">
    <%= render partial: "form" %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="card">
  <h4 class="card-header">New Category</h4>
  <div class="card-body">
    <%= render partial: "form" %>
  </div>
</div>

app/views/events/_comment_fields.html.erb
<div class="nested-fields">
  <div class="form-group row">
    <div class="input-field col">
      <%= f.input :comment, input_html: { class: "form-control" } %>
    </div>
  </div>
  <%= link_to_remove_association "Remove Comment", f, { class: "btn btn-secondary btn-sm" } %>
</div>

app/views/events/_comments_table.html.erb
<div class="col-12 col-md-6 comment-list">
  <table class="table table-sm">
    <thead>
      <tr>
        <th>Comments</th>
      </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.comment.capitalize %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.error_notification message: t(:'simple_form.error_notification.default_message', model: "Event") %>

  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>

  <%= f.input :title %>

  <%= f.input :description %>

  <div class="form-group row">
    <div class="input-field col">
      <%= f.label :start_time, "From" %>
      <%= f.datetime_local_field :start_time, class: "form-control" %>
    </div>
    <div class="input-field col">
      <%= f.label :end_time, "Until"  %>
      <%= f.datetime_local_field :end_time, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="input-field col event_file">
      <%= f.label :event_file, "Upload File" %>
      <%= f.file_field :event_file, class: "form-control" %>
    </div>
    <div class="input-field col event_category">
      <%= f.association :category %>
    </div>
  </div>

  <div class="form-group row">
    <div class="input-field col">
      <h5>Comments</h5>
      <div id="comments">
        <%= f.simple_fields_for :comments do |comment| %>
          <%= render "comment_fields", f: comment %>
        <% end %>
      </div>
      <div class="links mt-3">
        <%= link_to_add_association "Add Comment", f, :comments, { class: "btn btn-success btn-sm" } %>
      </div>
    </div>

    <div class="input-field col">
      <h5>Tasks</h5>
      <div id="tasks">
        <%= f.simple_fields_for :tasks do |task| %>
          <%= render "task_fields", f: task %>
        <% end %>
      </div>
      <div class="links mt-3">
        <%= link_to_add_association "Add Task", f, :tasks, { class: "btn btn-success btn-sm" } %>
      </div>
    </div>
  </div>

  <%= f.input :private, as: :radio_buttons, input_html: { class: "ml-2" } %>

  <div class="form-group row">
    <%= f.input :active, as: :radio_buttons, input_html: { class: "ml-2" } %>
    <div class="input-field col-3" id="active-date-field">
      <%= f.label :active_date, "Set Active Date?"  %>
      <%= f.date_field :active_date, html5: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, { class: "btn btn-info" }%>
    <%= link_to "Cancel", dashboard_path, { class: "btn btn-secondary" } %>
  </div>
<% end %>

app/views/events/_task_fields.html.erb
<div class="nested-fields">
  <div class="input-field">
    <%= f.input :description, input_html: { class: "form-control" } %>
  </div>
  <div class="input-field col-3 pl-0">
    <%= f.input :priority, collection: Task.priorities, input_html: { class: "form-control" }, label_method: :first, value_method: :first %>
  </div>
  <%= link_to_remove_association "Remove Task", f, { class: "btn btn-secondary btn-sm" } %>
</div>

app/views/events/_tasks_table.html.erb
<div class="col-12 col-md-6 task-list">
  <table class="table table-sm">
    <thead>
      <tr>
        <th>Tasks</th>
        <th>Priority</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.description.capitalize %></td>
          <td><%= task.priority.capitalize %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/edit.html.erb
<div class="card">
  <h4 class="card-header"><%= "Edit #{@event.title.titleize}" %></h4>
  <div class="card-body">
    <%= render partial: "form" %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-12 col-md-2">
    <div class="row">
      <%= link_to "New Event", new_event_path, class:"btn btn-success" %>
    </div>
    <div class="row mt-4">
      <h6>Categories</h6>
      <div class="list-group col-12">
        <% @categories.each do |category| %>
          <%= link_to category.name, edit_category_path(category), style:"background-color:#{category.color}; color:white", class:"list-group-item list-group-item-action small" %>
        <% end %>
        <%= link_to "New Category", new_category_path, class:"list-group-item list-group-item-action small" %>
      </div>
    </div>

  </div>
  <div class="col-12 col-md-10">
    <%= month_calendar events: @events do |date, events| %>
      <%= date.day %>
      <% events.each do |event| %>
        <div>
          <%= link_to event.title, event_path(event), style:"color:#{listing_color(event)}" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="card">
  <h4 class="card-header">New Event</h4>
  <div class="card-body">
    <%= render partial: "form" %>
  </div>
</div>

app/views/events/show.html.erb
<div class="card">
  <h4 class="card-header"><%= @event.title.titleize %>
    <% if @event.category %>
      <span class="badge badge-pill ml-2" style="<%= "background-color:#{@event.category.color}; color:white" %>"><%= @event.category.name %></span>
    <% end %>
    <small class="text-muted float-right"><%= "#{@event.start_time.to_s(:day_month_time)} - #{@event.end_time.to_s(:day_month_time)}" %></small></h4>
  <div class="card-body">

    <% if @event.description %>
      <p><strong>Description: </strong><%= @event.description.capitalize %></p>
    <% end %>

    <% if @event.event_file? %>
      <p>Attachment: <%= link_to @event.event_file.original_filename, @event.event_file.url %></p>
    <% end %>

    <div class="row">
        <% if @comments %>
          <%= render partial: "comments_table", locals: { comment: @comment } %>
        <% end %>

      <% if @tasks %>
        <%= render partial: "tasks_table", locals: { task: @task } %>
      <% end %>
    </div>

    <div class="row mt-3">
      <div class="col-3">
        <%= link_to "Edit", edit_event_path(@event), { class: "btn btn-info" } %>
        <%= link_to "Delete", event_path(@event), data: { confirm: "Are you sure?" }, class: "btn btn-danger", method: :delete  %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="<%= flash_class(message_type) %> alert-dismissable fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= message %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a href="/" class="navbar-brand"><i class="fa fa-calendar"></i> SimpleCal</a>
  <span class="navbar-text">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <li class="nav-item"><%= link_to "Log Out", destroy_user_session_path, {class: "nav-link", method: :delete} %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Log In", new_user_session_path, {class: "nav-link"} %></li>
      <% end %>
    </ul>
  </span>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"/>
  </head>

  <body>
    <header>
      <%= render partial: "layouts/navbar" %>
    </header>
    <main>
      <div class="container">
        <%= render partial: "layouts/flash_messages", flash: flash %>
        <div class="pt-4">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading col-6 mx-auto">
    <%= link_to calendar.url_for_previous_view do %>
      <i class="fa fa-angle-double-left"></i>Previous
    <% end %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to calendar.url_for_next_view do %>
      Next<i class="fa fa-angle-double-right"></i>
    <% end %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>